---
title: "Individual assignment"
author: 
  - Jon Ingi Hlynsson
date: "`r Sys.Date()`"
output: 
  html_document:
    toc_depth: 3
    toc: yes
    toc_float: no
    code_folding: hide
    fig_caption: yes
    theme: flatly
    highlight: textmate
    css: default.css
bibliography: refs.bib
citation-style: apa-annotated-bibliography.csl
---

```{r setup and packages, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # this is included by default in markdown 

## clean the environment -----
rm(list = ls(all=T)) # remove all variables (all=T takes care of hidden objects)
graphics.off() # turn off plots
cat("\014") # clear the console ("\014" refers to the "L" key on the keyboard)
## ----

## an error message and the fix ------------------------------------------------
## I sometimes get the error:

# Error in gregexpr(calltext, singleline, fixed = TRUE) : 
# regular expression is invalid UTF-8

## the following code usually fixes it:
# .rs.restartR() # this restarts the session

## However I've also had to go into *file* and *reopen with Encoding* and choose 
#  UTF-8
# the following code can also does that
# options(encoding = "UTF-8")

# This extra information is added here as a comment to make readers aware of the
# potential that this has happened on my end but likewise has a fix.
## -----------------------------------------------------------------------------


## import packages ----
library(tidyverse) # for pipe friendly operations and ggplot
library(ggpubr) # for convenient plotting 
library(kableExtra) # for nice tables
library(knitr) # for kable function and markdown output
library(rstanarm) # for Bayesian models 
## ---

## Set working directory ----
# Remember to set the working directory to the RELEVEANT position
```



```{r Read in data, results='hide', class.source = "fold-hide", echo=F}
d_full <- read.table("https://raw.githubusercontent.com/JonHlynsson/PSMT59-Statistics-I/master/data/d1_soundscape.txt", 
                     header = T, sep = ",")
```


```{r Create a new data set with all participants, echo=F, results='hide'}
## Regarding the construction of a new dataset from d_full ---- 

# The data is applicable to a data-analysis. First a new dataset needs to be 
# constructed with the aim of binding together the cognitive measures 
# back-ward digit span task (DBS) and `dual n-back task (DNB)`. 
# Thereafter, the `dnb` and `bds` variables need to be z-scored to make the two 
# attentional cognitive measures comparable. Finally, the z-scored variables 
# dnb and bds can be combined.

## ----

## Predata selection ----
d_full_pre <- d_full[, c(1, 2, 3, 5, 7)] # select pretest data
d_full_pre$testing <- rep(0, nrow(d_full_pre)) # add dummy variable to indicate 
names(d_full_pre) <- c("id", 
                       "soundscape_type", 
                       "bds", 
                       "dnb",
                       "guessed_purpose", 
                       "testing") # rename variables because I already have an
#                                   indication variable
head(d_full_pre) 
str(d_full_pre)
## ----


## Postdata selection ----
d_full_post <- d_full[, c(1, 2, 4, 6, 7)] # select postdata
d_full_post$testing <- rep(1, nrow(d_full_post)) # add dummy var to indicate
names(d_full_post) <- c("id", 
                        "soundscape_type", 
                        "bds", 
                        "dnb", 
                        "guessed_purpose", 
                        "testing") # rename variables because I already have an
#                                    indication variable
head(d_full_post)
str(d_full_post)
## ----


## Create a new combined dataset with r-bind ----
d <- rbind(d_full_pre, d_full_post)
head(d)
summary(d)
str(d)
## ----

## remove pre and post data placeholder datasets ----
rm(d_full_pre)
rm(d_full_post)
## ----


## Make id, soundscape_type, guessed_purpose, and post as factors ----
d$id <- factor(d$id)
d$soundscape_type <- factor(d$soundscape_type, labels = c("Natural", "Urban"))
d$guessed_purpose <- factor(d$guessed_purpose, labels = c("No", "Yes"))
d$testing <- factor(d$testing, labels = c("Pretest", "Posttest"))
head(d)
str(d)
summary(d)
## ----


## Create z-score function ----
z_score <- function(x){
  out <- (x - mean(x, na.rm = TRUE))/sd(x, na.rm = TRUE)
  out
}
## ----


## z-score the difference score ----
d$zDNB <- z_score(d$dnb)
d$zBDS <- z_score(d$bds)
head(d)
## ----


## combine z-variables ----
d$CogTest <- (d$zDNB + d$zBDS)/2
head(d)
str(d)
summary(d)
psych::describe(d)
```

```{r, include=T, echo=F}
# Thanks to Mats Nilsson for helping me understanding the aggregate function 
dstat <- aggregate(list(outcome = d$CogTest), 
                   list(condition = d$soundscape_type, time = d$testing), 
                   mean, na.rm = TRUE)
dstat$sd_out <- aggregate(list(sd_out = d$CogTest), 
                   list(condition = d$soundscape_type, time = d$testing), 
                   sd, na.rm = TRUE)$sd_out

dstat %>% select(c("condition", "outcome", "sd_out")) %>%  
  kable(digits = 2,
        caption = "Supplementary table 1. Means and standard deviations by soundscape type and time of testing", 
        align = c("l", "c", "c", "r"),
        col.names = c("Type of soundscape", "Mean", "sd")) %>% 
  kable_classic() %>% 
  kable_styling(full_width = T, html_font = "Times") %>% 
  group_rows(group_label = "Pretest", start_row = 1, end_row = 2) %>% 
  group_rows(group_label = "Posttest", start_row = 3, end_row = 4)

## interpretation --------------------------------------------------------------
```
As can be seen in supplementary table 1, the mean of the post-test among those whom were in the Natural soundscape is the highest.
 
```{r Using difference scores to better interperate the results, results='hide', echo=F}

# replicate d_full
d2 <- d_full

# create difference scores
d2$bds_diff <- (d2$bds_post - d2$bds_pre) 
d2$dnb_diff <- (d2$dnb_post - d2$dnb_pre)

# z score the difference scores to be able to add the different attentional tasks together
d2$bds_diff_Z <- z_score(d2$bds_diff)
d2$dnb_diff_Z <- z_score(d2$dnb_diff)
round(mean(d2$dnb_diff_Z), 5) # sanity check - we want the value 0
round(mean(d2$bds_diff_Z), 5) # sanity check - we want the value 0
sd(d2$bds_diff_Z) # sanity check - should give the value 1
sd(d2$dnb_diff_Z) # sanity check - should give the value 1

# create composite variable from the difference scores
d2$CogTest <- (d2$bds_diff_Z + d2$dnb_diff_Z)/2

# make soundscape a factor and let Urban be the reference group
d2$soundscape_type <- factor(d2$soundscape_type, levels = c("U", "N"))

# do a crude linear model
crude <- stan_glm(CogTest ~ soundscape_type, 
                  data = d2, 
                  refresh = F, 
                  seed = 1995)
summary(crude)
round(coef(crude), 2) 
round(posterior_interval(crude, prob = .89), 2)
```

```{r Crude coefficients ronded to two digets, class.source = "fold-hide", comment="", echo=F, results='hide'}
round(coef(crude), 2)
```

```{r calculate crude posterior, echo=F}
crudePosterior <- posterior_interval(crude, prob = .89) 
# note: THIS IS A TABLE!
# Because the code above can be conceived of as a table, sigma is omitted 
# leaving only the intercept and coefficient of the crude model shown below
```


```{r show crude posterior, class.source = "fold-hide", comment="", echo=F, results='hide'}
round(crudePosterior[-3, ], 2)  
```






```{r calculations of descriptives for the models, echo=F}
d2$soundscape_type <- factor(d2$soundscape_type, labels = c("Urban", "Natural"))

# descriptives for the crude model
d2statCrude <- aggregate(list(mean_outcome = d2$CogTest), 
                   list(condition = d2$soundscape_type), 
                   mean, na.rm = TRUE)

d2statCrude$sd_out <- aggregate(list(sd_out = d2$CogTest), 
                   list(condition = d2$soundscape_type), 
                   sd, na.rm = TRUE)$sd_out

colnames(d2statCrude) <- c("Type of soundscape", "Mean", "sd")


# descriptives for the adjusted model
d2statAdjusted <- aggregate(list(mean_outcome = d2$CogTest), 
                   list(condition = d2$soundscape_type, Naive = d2$guessed_purpose), 
                   mean, na.rm = TRUE)

d2statAdjusted$sd_out <- aggregate(list(sd_out = d2$CogTest), 
                   list(condition = d2$soundscape_type, Naive = d2$guessed_purpose), 
                   sd, na.rm = TRUE)$sd_out

colnames(d2statAdjusted) <- c("Type of soundscape", "Naïvity of participants", 
                              "Mean", "sd")
```

<br><br><br><br><br><br><hr>


<br> 

```{r, results='hold', out.width="10%", include=T, echo=F, size="50%"}
# See supplementary table 2 for descriptives of the models

# view descriptives for crude
c <- d2statCrude %>% kable(digits = 2, caption = "**Crude descriptives**") %>% 
  kable_classic() %>% kable_styling(full_width = T, html_font = "Times")
```


```{r, results='hold', out.width="10%", include=T, echo=F, size="50%"}
# view descriptives for adjusted
a <- d2statAdjusted %>% select(c("Type of soundscape", "Mean", "sd")) %>% 
  kable(digits = 2, col.names = c("**Adjusted descriptives**", "", "")) %>% 
  kable_classic() %>% 
  kable_styling(full_width = T, html_font = "Times") %>% 
  group_rows(group_label = "Naïve participants", start_row = 1, end_row = 2, 
             indent = F, bold = F, italic = T) %>% 
  group_rows(group_label = "Non-naïve participants", start_row = 3, end_row = 4, 
             indent = F, bold = F, italic = T)
```


:::::{.pull-left}
<div style="font-family: Times;">Supplementary table 2. Descriptive statistics for the crude and adjusted models</div>


```{r, echo=F}
c
a
```
:::::

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
Supplimentary table 2 shows the means and dispersion of the crude and adjusted models.

<br><br><br><br><br><br><br><br><hr>
`r r2symbols::symbol("copyright")` Jon Ingi Hlynsson - last edited `r Sys.Date()`

